version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: NODE_ENV=development yarn
      - run: NODE_ENV=development yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ];
            then
              npx semantic-release
            fi
